#!/bin/sh

#parse through txt files to check listed ip addresses
for FILE in /path/to/folder/*.txt;do
    date
    cat $FILE |  while read output
    do
        ping -c 1 "$output" > /dev/null
        if [ $? -eq 0 ]; then
        echo "node $output is up"
        else
        echo "node $output is down"
        fi
    done
done
